name: ayn_app
description: AYN - Smart Vision Assistant for the Blind
publish_to: 'none'
version: 1.3.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0
  vibration: ^1.8.4
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  flutter_compass: ^0.8.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
